Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.2.111" # This will be IP address of your VM

  config.vm.synced_folder "./vagrant_data/", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Running init script. This will update packages and install basic programs.
    cd /vagrant_data/ && sudo chmod +x init.sh && sudo ./init.sh
  SHELL
end
